title: 小さなVNパッチ。
description: Here you can find a few small patches for some visual novels...
url: "https://meru.github.io/svnp" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "/svnp" # the subpath of your site, e.g. /blog

# Comments
discus_identifier:

# Social settings
twitter_url: https://twitter.com/meruppi
facebook_url:
googleplus_url:
instagram_url:
github_url:
